### ISSUE TITLE
Add option to always regenerate signature file

### ISSUE THREAD

**Issue by guptadeepanshu** [martinbonnin/vespene#10]
It's not necessary that the GPG signature/key used by JCenter would be the same as the one people may create for maven central. In fact, it may be more likely. So different versions would be signed with different keys which doesn't seem like a good idea.

**Comment by guptadeepanshu** [comment]
I might have been too quick to open this issue.

I haven't checked if OSSRH accepts the signatures autogenerated by jcenter. If it does, then this option may not be needed. 

Different versions are bound to be singed with different keys eventually, as the original keys expire. So, having some versions signed by personal key, and some signed by jcenter's autogenerated key doesn't seem that bad.

**Comment by martinbonnin** [comment]
My understanding is that you can have any amount of keys sign artifacts as long as they are published to a public keyserver. 

The reasoning behind keeping the jcenter signature is to make the move have the smallest impact area as possible so only creating new signature if any of the content changes, like pom files for an example.
